#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:00:00
#SBATCH --job-name=CIRApp
#SBATCH --output=slurm_output_run_app_%j.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate dl2024 # my conda environment for the project on snellius

cd $HOME/multimedia-analytics/cir_app
export PYTHONPATH=$PYTHONPATH:$(pwd)

# Launch in production (no debug, no autoreload)
python run.py
